// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// welfare_stats_all
NumericVector welfare_stats_all(NumericVector y, NumericVector w, double pov_line, double gap_line, double sev_line, double prosp_line);
RcppExport SEXP _wiseapp_welfare_stats_all(SEXP ySEXP, SEXP wSEXP, SEXP pov_lineSEXP, SEXP gap_lineSEXP, SEXP sev_lineSEXP, SEXP prosp_lineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type pov_line(pov_lineSEXP);
    Rcpp::traits::input_parameter< double >::type gap_line(gap_lineSEXP);
    Rcpp::traits::input_parameter< double >::type sev_line(sev_lineSEXP);
    Rcpp::traits::input_parameter< double >::type prosp_line(prosp_lineSEXP);
    rcpp_result_gen = Rcpp::wrap(welfare_stats_all(y, w, pov_line, gap_line, sev_line, prosp_line));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wiseapp_welfare_stats_all", (DL_FUNC) &_wiseapp_welfare_stats_all, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_wiseapp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
