# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute All Nine Welfare Aggregation Statistics in One Pass
#'
#' Single-pass kernel mirroring \code{resolve_agg_fn()} exactly (to float
#' tolerance): one scan in row order for the scan statistics plus one
#' (value, index)-stable sort shared by the weighted/unweighted median and
#' the Gini. The stable sort order is attached as attribute \code{"order"}
#' so callers can reuse it for downstream gradient computations.
#'
#' @param y Numeric welfare values.
#' @param w Numeric weights, or an empty vector for unweighted statistics.
#' @param pov_line Headcount threshold; NA yields NA for headcount_ratio.
#' @param gap_line Poverty-gap threshold; NA yields NA for poverty_gap.
#' @param sev_line Poverty-severity threshold; NA yields NA for fgt2.
#' @param prosp_line Prosperity threshold, hardcoded $28/day by the app.
#'
#' @return Named numeric vector of length 9 with the statistics in the fixed
#'   order mean, median, total, headcount_ratio, poverty_gap,
#'   poverty_severity, gini, prosperity_gap, avg_poverty, plus attribute
#'   \code{"order"}: the 1-based stable sort index of \code{y}.
#'
#' @noRd
welfare_stats_all <- function(y, w, pov_line, gap_line, sev_line, prosp_line) {
    .Call(`_wiseapp_welfare_stats_all`, y, w, pov_line, gap_line, sev_line, prosp_line)
}

